name: json
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: main

      - name: Checkout Tools
        uses: actions/checkout@v4
        with:
          repository: drawthingsai/draw-things-community
          token: ${{ secrets.GHA_BOT_ORG_ACCESS_TOKEN }}
          path: tools

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.GHA_BOT_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHA_BOT_AWS_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Configure S3 / R2
        run: |
          aws configure set default.s3.max_concurrent_requests 2

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Install Swift dependencies
        run: |
          sudo apt-get install clang libicu-dev
          wget https://download.swift.org/swift-5.10-release/ubuntu2204/swift-5.10-RELEASE/swift-5.10-RELEASE-ubuntu22.04.tar.gz
          tar xzf swift-5.10-RELEASE-ubuntu22.04.tar.gz
          echo "$(pwd)/swift-5.10-RELEASE-ubuntu22.04/usr/bin" >> $GITHUB_PATH

      - name: Setup clang
        run: |
          sudo apt -y install libpng-dev libjpeg-dev libatlas-base-dev libblas-dev libgsl-dev clang llvm libdispatch-dev libomp-dev liblinear-dev libfftw3-dev libtesseract-dev
          cd "${GITHUB_WORKSPACE}/tools"
          ./Scripts/setup_clang.sh /usr
          ./Scripts/install.sh
          echo "build --config=clang" >> "${GITHUB_WORKSPACE}/tools/.bazelrc.local"
          bazel build Apps:ModelConverter

      - name: Run JSON generation.
        run: |
          cd "${GITHUB_WORKSPACE}/main"
          python3 scripts/models_json.py
          python3 scripts/loras_json.py
          git config --global user.email "docbot@github.com"
          git config --global user.name "docbot"
          git commit -a -m "Update metadata with converted models / LoRAs."
          git pull --rebase && git push

      - name: Clean up json branch
        run: |
          cd "${GITHUB_WORKSPACE}/main"
          git branch -D json || true
          git checkout -b json
          mkdir -p docs
          mv *.json ./docs
          echo "models.drawthings.ai" > ./docs/CNAME
    
      - name: Add and commit documentation
        run: |
          cd "${GITHUB_WORKSPACE}/main"
          git add "docs/*" && git commit -m "Update docs."

      - name: Push the new branch
        run: |
          cd "${GITHUB_WORKSPACE}/main"
          git push --force origin json:json

